plugins {
    id 'groovy-gradle-plugin'
}

file('../gradle.properties').withInputStream { is ->
    extensions.extraProperties.set(
            'gradleProperties',
            new Properties().tap { load(is) }
    )
}

def projectYml = new org.yaml.snakeyaml.Yaml().load(file('../project.yml').text) as Map

allprojects { project ->
    gradleProperties.stringPropertyNames().each { key ->
        project.extensions.extraProperties.set(
                key,
                gradleProperties.getProperty(key)
        )
    }

    project.extensions.extraProperties.set('projectTitle',       projectYml.project.title as String)
    project.extensions.extraProperties.set('projectDescription', projectYml.project.description as String)
    project.extensions.extraProperties.set('projectOrg',         projectYml.project.org as String)
    project.extensions.extraProperties.set('githubOrg',          projectYml.github.org as String)
    project.extensions.extraProperties.set('githubProject',      projectYml.github.project as String)
    project.extensions.extraProperties.set('projectLicense',     projectYml.license.name as String)
    project.extensions.extraProperties.set('projectContributors', projectYml.contributors ?: [:])
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:${gradleProperties.grailsVersion}")
    implementation 'org.apache.groovy:groovy-yaml'
    implementation 'cloud.wondrify:asset-pipeline-gradle'
    implementation "com.adarshr:gradle-test-logger-plugin:${gradleProperties.testLoggerVersion}"
    implementation 'org.apache.grails:grails-gradle-plugins'
    implementation 'org.apache.grails.gradle:grails-publish'
    implementation "org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin:${gradleProperties.asciidoctorVersion}"
}
