plugins {
    id 'config.compile'
    id 'config.grails-plugin'
    id 'config.project-metadata'
    id 'config.publish'
    id 'config.testing'
}

version = projectVersion
group = "io.github.gpc"

dependencies {
    profile 'org.apache.grails.profiles:web-plugin'
    console 'org.apache.grails:grails-console'

    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'

    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
    testImplementation 'org.apache.grails:grails-dependencies-starter-web'
    testImplementation 'org.apache.grails:grails-dependencies-test'

    // export plugin specific dependencies
    api 'com.opencsv:opencsv:5.12.0'

    api 'com.github.librepdf:openpdf:1.4.2'
    api 'com.github.librepdf:openrtf:1.2.1'
    runtimeOnly 'xerces:xercesImpl:2.12.2'

    api 'org.odftoolkit:simple-odf:0.9.0'
    api 'org.apache.poi:poi:5.5.1'
    api 'org.apache.poi:poi-ooxml:5.5.1'

    api 'commons-beanutils:commons-beanutils:1.11.0'
    api 'commons-codec:commons-codec:1.21.0'

}

extensions.configure(org.apache.grails.gradle.publish.GrailsPublishExtension) {
    it.githubSlug = "${githubOrg}/${githubProject}"
    it.license.name = projectLicense
    it.title = projectTitle
    it.desc = projectDescription
    it.organization {
        it.name = projectOrg
        it.url = "https://github.com/${githubOrg}"
    }
    it.setDevelopers(projectContributors as Map)
}
