import org.gradle.api.publish.maven.tasks.GenerateMavenPom

plugins {
    id 'config.compile'
    id 'config.grails-plugin'
    id 'config.publish'
    id 'config.testing'
    id 'config.contributors'
}

version = projectVersion
group = "io.github.gpc"

dependencies {
    profile 'org.apache.grails.profiles:web-plugin'
    console 'org.apache.grails:grails-console'

    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'

    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
    testImplementation 'org.apache.grails:grails-dependencies-starter-web'
    testImplementation 'org.apache.grails:grails-dependencies-test'

    // export plugin specific dependencies
    api 'com.opencsv:opencsv:5.12.0'

    api 'com.github.librepdf:openpdf:1.4.2'
    api 'com.github.librepdf:openrtf:1.2.1'
    runtimeOnly 'xerces:xercesImpl:2.12.2'

    api 'org.odftoolkit:odfdom-java:0.13.0'
    api 'org.apache.poi:poi:5.5.1'
    api 'org.apache.poi:poi-ooxml:5.5.1'

    api 'commons-beanutils:commons-beanutils:1.11.0'
    api 'commons-codec:commons-codec:1.21.0'

}

extensions.configure(org.apache.grails.gradle.publish.GrailsPublishExtension) {
    it.artifactId = project.name
    it.githubSlug = "${githubOrg}/${githubProject}"
    it.license.name = 'Apache-2.0'
    it.title = "${projectTitle}"
    it.desc = "${projectDescription}"
    it.organization {
        it.name = "${projectOrg}"
        it.url = "https://github.com/${githubOrg}"
    }
}

pluginManager.withPlugin('maven-publish') {
    tasks.withType(GenerateMavenPom).configureEach { pomTask ->
        dependsOn(tasks.named('fetchContributors'))
        doFirst {
            pomTask.pom.developers { spec ->
                contributorsData.get().each { String login, String displayName ->
                    spec.developer {
                        id = login
                        name = displayName
                    }
                }
            }
        }
    }
}
